use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'

container:
  image: python:3.7-slim

lint_task:
  install_script:
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint --version
    - ./bin/lint.py

test_task:
  install_script:
    - pip install -r requirements.txt
  script:
    - python3 --version
    #- python3 -m pytest --verbose
    - python3 ./test.py
