lint_task:
  container:
    image: python:3.7-slim
  install_script:
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint --version
    - pylint emanate

test_task:
  container:
    matrix:
      - image: python:3.7-slim
  install_script:
    - pip install -r requirements.txt
  script:
    - python3 --version
    #- python3 -m pytest --verbose
    - python3 ./test.py
