# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

container:
  image: python:3.7-slim
  additional_containers:
    - name: elasticsearch
      image: elasticsearch:7.6.2
      port: 9200
      cpu: 0.5
      memory: 1.5Gi

env:
  ELASTICSEARCH: "http://elasticsearch:9200"

lint_task:
  install_script:
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint --version
    - ./bin/lint.py

test_task:
  install_script:
    - pip install -r requirements.txt
    - "apt-get update && apt-get install -y curl"
  script:
    - python3 --version
    #- python3 -m pytest --verbose
    - python3 ./lib/render.py
    - ./bin/index.sh
    - python3 ./bin/test.py
