container:
  image: python:3.7-slim
  additional_containers:
    - name: elasticsearch
      image: elasticsearch:7.6.2
      port: 9200
      cpu: 1.0
      memory: 1Gi

env:
  ELASTICSEARCH: "http://elasticsearch:9200"

lint_task:
  install_script:
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint --version
    - ./bin/lint.py
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'

test_task:
  install_script:
    - pip install -r requirements.txt
  script:
    - python3 --version
    #- python3 -m pytest --verbose
    - python3 ./lib/render.py
    - python3 ./bin/test.py
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
