safe: true
include: [_headers]
exclude: [.gitignore, _bin, CNAME, LICENSE, Gemfile, Gemfile.lock]
timezone: America/New_York
name: "Part Info"

url: https://part-info.netlify.com

defaults:
  -
    scope:
      path: "" # All files in the project.
    values:
      layout: "default"
  -
    scope:
      path: "parts" # All files under /parts.
    values:
      part: true
      layout: "part"
  -
    scope:
      path: "categories" # All files under /categories.
      type: "posts"
    values:
      layout: "category"
  -
    scope:
      path: "ds" # All files under /ds
    values:
      layout: "datasheet-redirect"
